import Head from 'next/head';
import Link from 'next/link';
import react from 'react';

export default function Layout({ title , children}) {
  return (
        <>
            <Head>
                <title>{title ? title:'Amazona'}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='flex flex-col min-h-screen justify-between'>
                <header>
                    <nav className='flex h-12 items-center px-4 justify-between shadow-md'>
                        <Link href="/" className= 'text-lg font-bold'>
                            Amazona
                        </Link>
                        <div>
                            <Link className='p-2' href="/Cart">Cart</Link>
                            <Link className='p-2' href="/Login">Login</Link>
                            
                        </div>

                    </nav>
                </header>
                <main className='container px-4 mt-4 m-auto'>{children}</main>
                <footer className='flex justify-center items-center h-10 shadow-inner'>Copyright @ 2022 Amazona</footer>
            </div>
        </>
    
  )
}
