const data = {
    products:[
        {   name:'Roadster-Shirt',
            slug:'Branded-shirt',
            category:'Shirts',
            image:'/images/shirt1.jpg',
            price:400,
            brand:'Roadster',
            rating:4.5,
            numReviews:10,
            countInStock:30,
            description:'A popular shirt',
        },
        {   name:'Raymond-Shirt',
            slug:'Raymond-Shirt',
            category:'Shirts',
            image:'/images/shirt2.jpg',
            price:1000,
            brand:'Roadster',
            rating:4.5,
            numReviews:10,
            countInStock:30,
            description:'A popular shirt',
        },
        {   name:'Puma-Shoes',
            slug:'Branded-shoes',
            category:'Footwear',
            image:'/images/shoes1.jpg',
            price:2000,
            brand:'Puma',
            rating:4.7,
            numReviews:15,
            countInStock:45,
            description:'Popular shoes',
        },
        {   name:'Addidas-Shoes',
            slug:'Addidas',
            category:'Footwear',
            image:'/images/shoes2.jpg',
            price:3000,
            brand:'Addidas',
            rating:4.9,
            numReviews:15,
            countInStock:50,
            description:'Popular shoes',
        },
    ],
};

export default data;

